### ISSUE TITLE
Graphics (background image, logo/favicon)

### ISSUE THREAD

**Issue by matthuska** [mf1-innovation/mf1-innovation.github.io#15]
We need a header/footer graphic. The default is to use the same image for both, but it doesn't have to be that way.

We also need a logo and/or favicon (the tiny icon that is shown for tabs and bookmarks)

**Comment by hoelzer** [comment]
Regarding a logo (and small favicon), what do you think about:

![2024-01-16-MF1-Innovations-light-bulb](https://github.com/mf1-innovation/mf1-innovation.github.io/assets/14393703/1039f4a6-c669-4111-9598-fbb2cf41d2b5)

which I generated w/ DALL-E.

**Comment by matthuska** [comment]
Not going to lie, that looks like it was generated by an AI and it's not my favorite thing in the world 😄 Maybe something with a similar theme but a little more minimal/logo style. I can play with some image generation tools too and see if I can get something that fits what I'm imagining.

**Comment by hoelzer** [comment]
Yeah, fair enough bc that's exactly what it is :D 

@huguesrichard also mentioned that we could use it as a template but make a more minimalistic Inkscape version of it. We can also think about smt totally different (maybe even during the retreat...).
